# Generated by Django 3.2 on 2021-04-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=20)),
                ('room_name', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'rooms',
            },
        ),
    ]
