# Generated by Django 3.2 on 2021-04-22 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='email_user',
            new_name='email',
        ),
    ]
