# Generated by Django 3.2 on 2021-04-07 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='room_id',
        ),
    ]
