# Generated by Django 3.2 on 2021-05-03 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_email_user_useraccount_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.rooms')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('count', models.CharField(max_length=255)),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.rooms')),
            ],
        ),
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
