# Generated by Django 3.2 on 2021-05-06 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20210503_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_list_title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255)),
                ('profile_pic', models.CharField(max_length=1000)),
                ('user_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='count',
            new_name='vote_id',
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_id', models.CharField(max_length=255)),
                ('song_list_id', models.IntegerField()),
                ('queue_history', models.CharField(max_length=255)),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.rooms')),
            ],
        ),
        migrations.AlterField(
            model_name='vote',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.users'),
        ),
    ]
