# Generated by Django 3.2 on 2021-05-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_rooms_roomtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='roomType',
            field=models.BooleanField(default=True),
        ),
    ]
