# Generated by Django 3.2 on 2021-05-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_alter_rooms_roomtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='room_id',
            field=models.CharField(default=True, max_length=20),
        ),
    ]
